import pandas as pd
df = pd.read_csv(r'C:\Users\91774\OneDrive\customer_shopping_behavior.csv')
df.head()
df.info()
df.describe()
df.isnull().sum()
df["Review Rating"] = df.groupby('Category')
["Review Rating"].transform(lambda x: x.fillna(x.median()))
df.columns = df.columns.str.lower()
df.columns =  df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount_usd'})
df = df.rename(columns={'frequency_of_purchases':'freq_of_purchases'})
